<?php
$config=[
    'add_member_rules'=>[
        [
            'field'=>'fullName',
            'label'=>'Full Name',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact',
            'label'=>'contact',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required|alpha'
        ],
        [
            'field'=>'memberStatus',
            'label'=>'Member Status',
            'rules'=>'required'
        ],
        [
            'field'=>'booksAllowed',
            'label'=>'Books Allowed',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'cnic',
            'label'=>'cnic',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required'
        ]
    ],
    'modifyBook'=>[
        [
            'field'=>'title',
            'label'=>'book title',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'author',
            'label'=>'author',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'languageId',
            'label'=>'language',
            'rules'=>'required'
        ],
        [
            'field'=>'cost',
            'label'=>'cost',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'notes',
            'label'=>'notes',
            'rules'=>'alpha_numeric_spaces'
        ],
        [
            'field'=>'subCatId',
            'label'=>'subCat',
            'rules'=>'required'
        ],
        [
            'field'=>'bookStatus',
            'label'=>'bookStatus',
            'rules'=>'required'
        ],
        [
            'field'=>'publisher',
            'label'=>'publisher',
            'rules'=>'required|alpha_numeric_spaces'
        ]
    ],
    'checkIn'=>[
        [
            'field'=>'bookNumber',
            'label'=>'Book Number',
            'rules'=>'required|numeric'
        ]
    ],
    'newBookCategory'=>[
        [
            'field'=>'category',
            'label'=>'category',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'subCat',
            'label'=>'Sub Cat',
            'rules'=>'callback_textRegex'
        ]
    ],
    'newBookLanguage'=>[
        [
            'field'=>'language',
            'label'=>'language',
            'rules'=>'required|alpha|is_unique[table_language.language]'
        ]
    ],
    'modify_institute_rules'=>[
        [
            'field'=>'name',
            'label'=>'Name',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact',
            'label'=>'contact',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'establishedIn',
            'label'=>'established In',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'registrationNo',
            'label'=>'registration No',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dueDays',
            'label'=>'dueDays',
            'rules'=>'required|numeric|max_length[3]'
        ],
        [
            'field'=>'monthlyFees',
            'label'=>'monthlyFees',
            'rules'=>'required|numeric|max_length[3]'
        ]
    ],
    'profile_email_rule'=>[
        [
            'field'=>'userEmail',
            'label'=>'user Email',
            'rules'=>'required|valid_email|is_unique[users.userEmail]'
        ]
    ],
    'profile_userName_rule'=>[
        [
            'field'=>'userName',
            'label'=>'user Name',
            'rules'=>'required|alpha_numeric|is_unique[users.userName]'
        ]
    ],
    'profile_fields_rule'=>[
        [
            'field'=>'firstName',
            'label'=>'First Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'lastName',
            'label'=>'Last Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretQuestion',
            'label'=>'Secret Question',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretAnswer',
            'label'=>'Secret Answer',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ]
    ],
];
