<?php
$config=[
    'add_article'=>[
        [
            'field'=>'productName',
            'label'=>'productName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'productCode',
            'label'=>'productCode',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'costPrice',
            'label'=>'costPrice',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'sellPrice',
            'label'=>'sellPrice',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'status',
            'label'=>'status',
            'rules'=>'required|numeric'
        ]
    ],
    'add_order'=>[
        [
            'field'=>'orderDate',
            'label'=>'orderDate',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'quantityRequired',
            'label'=>'Quantity',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'buyerName',
            'label'=>'Name',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'buyerContact',
            'label'=>'Contact',
            'rules'=>'required|numeric|min_length[11]|max_length[11]'
        ],
        [
            'field'=>'buyerEmail',
            'label'=>'Email',
            'rules'=>'valid_email'
        ],
        [
            'field'=>'buyerAddress',
            'label'=>'buyerAddress',
            'rules'=>'required'
        ],
        [
            'field'=>'buyerNearbyPlace',
            'label'=>'Nearby Place',
            'rules'=>'alpha_numeric_spaces'
        ],
        [
            'field'=>'buyerCity',
            'label'=>'City',
            'rules'=>'alpha_numeric_spaces'
        ],
        [
            'field'=>'aditionalInfo',
            'label'=>'Aditional Info',
            'rules'=>'alpha_numeric_spaces'
        ]
    ],
    'checkIn'=>[
        [
            'field'=>'bookNumber',
            'label'=>'Book Number',
            'rules'=>'required|numeric'
        ]
    ],
    'newBookCategory'=>[
        [
            'field'=>'category',
            'label'=>'category',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'subCat',
            'label'=>'Sub Cat',
            'rules'=>'callback_textRegex'
        ]
    ],
    'newBookLanguage'=>[
        [
            'field'=>'language',
            'label'=>'language',
            'rules'=>'required|alpha|is_unique[table_language.language]'
        ]
    ],
    'modify_institute_rules'=>[
        [
            'field'=>'name',
            'label'=>'Name',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact',
            'label'=>'contact',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'establishedIn',
            'label'=>'established In',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'registrationNo',
            'label'=>'registration No',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dueDays',
            'label'=>'dueDays',
            'rules'=>'required|numeric|max_length[3]'
        ],
        [
            'field'=>'monthlyFees',
            'label'=>'monthlyFees',
            'rules'=>'required|numeric|max_length[3]'
        ]
    ],
    'profile_email_rule'=>[
        [
            'field'=>'userEmail',
            'label'=>'user Email',
            'rules'=>'required|valid_email|is_unique[users.userEmail]'
        ]
    ],
    'profile_userName_rule'=>[
        [
            'field'=>'userName',
            'label'=>'user Name',
            'rules'=>'required|alpha_numeric|is_unique[users.userName]'
        ]
    ],
    'profile_fields_rule'=>[
        [
            'field'=>'firstName',
            'label'=>'First Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'lastName',
            'label'=>'Last Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretQuestion',
            'label'=>'Secret Question',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretAnswer',
            'label'=>'Secret Answer',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ]
    ],
];
